# Generated by Django 3.0.5 on 2020-06-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smallPrice', models.IntegerField()),
                ('largePrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smallPrice', models.IntegerField()),
                ('largePrice', models.IntegerField()),
                ('oneToppingSmall', models.IntegerField()),
                ('twoToppingsSmall', models.IntegerField()),
                ('threeToppingsSmall', models.IntegerField()),
                ('oneToppingLarge', models.IntegerField()),
                ('twoToppingsLarge', models.IntegerField()),
                ('threeToppingsLarge', models.IntegerField()),
                ('specialSmall', models.IntegerField()),
                ('specialLarge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smallPrice', models.IntegerField()),
                ('largePrice', models.IntegerField()),
                ('extraCheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.ExtraCheese')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubWithExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Extra')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Sub')),
            ],
        ),
        migrations.CreateModel(
            name='PastaWithServing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Servings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Serving')),
                ('pasta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Pasta')),
            ],
        ),
    ]
