# Generated by Django 3.0.5 on 2020-06-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20200602_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwithextra',
            name='extras_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.Extra'),
        ),
    ]
