# Generated by Django 3.0.5 on 2020-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='area',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='doorNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='street',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
