# Generated by Django 3.0.5 on 2020-06-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20200604_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subwithextra',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='subwithextra',
            name='sub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.Sub'),
        ),
    ]
